// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniversalInventoryManager.Console.Data;

#nullable disable

namespace UniversalInventoryManager.Console.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("UniversalInventoryManager.Console.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasDiscriminator<string>("ProductType").HasValue("Product");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("UniversalInventoryManager.Console.Models.ClothingProduct", b =>
                {
                    b.HasBaseType("UniversalInventoryManager.Console.Models.Product");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Clothing");
                });

            modelBuilder.Entity("UniversalInventoryManager.Console.Models.TechProduct", b =>
                {
                    b.HasBaseType("UniversalInventoryManager.Console.Models.Product");

                    b.Property<bool>("HasBattery")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Tech");
                });
#pragma warning restore 612, 618
        }
    }
}
